"""Agent 3: Patient Report Agent.

Takes the clinical assessment from Agent 2 and converts it into a
patient-friendly report written at a target health literacy level
(Flesch-Kincaid grade level 6-8).

Input: ClinicalAssessment
Output: PatientReport dataclass with plain-language summary
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from medlens.agents.reasoning import ClinicalAssessment
    from medlens.model import MedGemmaModel


@dataclass
class PatientReport:
    """Patient-friendly report output."""

    summary: str = ""
    what_we_found: str = ""
    what_it_might_mean: str = ""
    next_steps: str = ""
    questions_to_ask: list[str] = None
    flesch_kincaid_grade: float = 0.0
    raw_output: str = ""
    disclaimer: str = (
        "IMPORTANT: This report is generated by an AI assistant and is for "
        "informational purposes only. It is NOT a medical diagnosis. Please "
        "discuss these findings with your healthcare provider."
    )

    def __post_init__(self):
        if self.questions_to_ask is None:
            self.questions_to_ask = []


def compute_flesch_kincaid_grade(text: str) -> float:
    """Compute Flesch-Kincaid grade level for the given text.

    FK Grade = 0.39 * (words/sentences) + 11.8 * (syllables/words) - 15.59
    """
    sentences = max(len(re.split(r"[.!?]+", text.strip())), 1)
    words_list = text.split()
    num_words = max(len(words_list), 1)
    syllables = sum(_count_syllables(w) for w in words_list)

    grade = 0.39 * (num_words / sentences) + 11.8 * (syllables / num_words) - 15.59
    return round(max(grade, 0.0), 1)


def _count_syllables(word: str) -> int:
    """Estimate syllable count for an English word."""
    word = word.lower().strip(".,!?;:'\"")
    if not word:
        return 0
    count = len(re.findall(r"[aeiouy]+", word))
    if word.endswith("e") and not word.endswith("le"):
        count = max(count - 1, 1)
    return max(count, 1)


class PatientReportAgent:
    """Converts clinical output into patient-friendly language.

    This is the third and final agent in the pipeline. It takes the
    clinical assessment and produces a plain-language report suitable
    for patients, targeting Flesch-Kincaid grade level 6-8.
    """

    SYSTEM_PROMPT = (
        "You are a patient communication specialist. Convert the following clinical "
        "assessment into a patient-friendly report. Use simple, everyday language "
        "that someone with a 6th-8th grade reading level can understand. "
        "Structure the report as: 1) Brief summary, 2) What we found, "
        "3) What it might mean, 4) Next steps, 5) Questions to ask your doctor. "
        "Avoid medical jargon — if you must use a medical term, explain it in "
        "parentheses. Be reassuring but honest."
    )

    def __init__(self, model: MedGemmaModel) -> None:
        self.model = model

    def run(self, assessment: ClinicalAssessment) -> PatientReport:
        """Generate a patient-friendly report from clinical assessment.

        Args:
            assessment: Clinical assessment from Agent 2.

        Returns:
            PatientReport with plain-language content and FK score.
        """
        raise NotImplementedError("Patient report agent not yet implemented")
